org: rahav2001
app: server
service: server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
